sudo: false

language: python

cache: pip

python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6

env:
  global: 
    - TEST_RESILIENT_APPLIANCE=d2-direct.resilientsystems.com
    - TEST_RESILIENT_ORG="Resilient PS - Test"
    
matrix:
  fast_finish: true
  include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.4
        env: TOXENV=py34

install:
 - pip install tox
 - pip install 'git+ssh://git@github.ibm.com/Resilient/resilient-api.git#egg=co3&subdirectory=python/co3'
 - pip install 'git+ssh://git@github.ibm.com/Resilient/resilient-api.git#egg=resilient_circuits&subdirectory=python/resilient-circuits'
 - pip install 'git+ssh://git@github.ibm.com/Resilient/resilient-api.git#egg=pytest_resilient_circuits&subdirectory=python/pytest-resilient-circuits'

script:
 - ./run_tests.sh

notifications:
    slack: ibm-security:9xGeUjQaqaNY1qgBG6ORFaSl
